
 
# Setup
title:        [Idukay]
description: [portfolio]
google_analytics: [UA-54473427-1]
is_project_page: false
show_downloads: true

github:
  is_project_page: false
  
theme: jekyll-theme-leap-day
